# database configuration
database:
  test:
    adapter: mysql2
    database: pincode_test
  development:
    adapter: mysql2
    database: pinkode_development
  production:
    adapter: mysql2
    database: pincode_production
